// poller/src/writers/artifacts.ts
import type { Event } from '../sources/types.js'
import { writeFileAtomic } from './fs-utils.js'

export interface ArtifactPaths {
  commitMessage: string
  issueTitle: string
  issueBody: string
}

export async function writeArtifacts(
  paths: ArtifactPaths,
  events: Event[],
  date: string,
  digestMarkdown: string,
): Promise<void> {
  const counts = summarize(events)
  const summary = summaryLine(counts)

  const commitMessage =
    `data: ${summary} (${date})\n\n` +
    `Auto-generated by daily-poll.yml.\n`

  const issueTitle = `Daily Digest — ${date}`

  // Issue body is the digest markdown minus the frontmatter (frontmatter is noise inside an issue)
  const issueBody = stripFrontmatter(digestMarkdown)

  await writeFileAtomic(paths.commitMessage, commitMessage)
  await writeFileAtomic(paths.issueTitle, issueTitle + '\n')
  await writeFileAtomic(paths.issueBody, issueBody)
}

function summarize(events: Event[]): { added: number; removed: number; updated: number } {
  return {
    added: events.filter((e) => e.type === 'added').length,
    removed: events.filter((e) => e.type === 'removed').length,
    updated: events.filter((e) => e.type === 'updated').length,
  }
}

function summaryLine(c: { added: number; removed: number; updated: number }): string {
  const parts: string[] = []
  if (c.added > 0) parts.push(`+${c.added}`)
  if (c.removed > 0) parts.push(`-${c.removed}`)
  if (c.updated > 0) parts.push(`~${c.updated}`)
  if (parts.length === 0) return 'no changes'
  return `${parts.join(' / ')} plugins`
}

function stripFrontmatter(md: string): string {
  if (!md.startsWith('---\n')) return md
  const end = md.indexOf('\n---\n', 4)
  if (end === -1) return md
  return md.slice(end + 5).trimStart()
}
