// poller/src/writers/artifacts.ts
import type { Event } from '../sources/types.js'
import { writeFileAtomic } from './fs-utils.js'

export interface ArtifactPaths {
  commitMessage: string
}

export async function writeArtifacts(
  paths: ArtifactPaths,
  events: Event[],
  date: string,
): Promise<void> {
  const counts = summarize(events)
  const summary = summaryLine(counts)

  const commitMessage =
    `data: ${summary} (${date})\n\n` +
    `Auto-generated by daily-poll.yml.\n`

  await writeFileAtomic(paths.commitMessage, commitMessage)
}

function summarize(events: Event[]): { added: number; removed: number; updated: number } {
  return {
    added: events.filter((e) => e.type === 'added').length,
    removed: events.filter((e) => e.type === 'removed').length,
    updated: events.filter((e) => e.type === 'updated').length,
  }
}

function summaryLine(c: { added: number; removed: number; updated: number }): string {
  const parts: string[] = []
  if (c.added > 0) parts.push(`+${c.added}`)
  if (c.removed > 0) parts.push(`-${c.removed}`)
  if (c.updated > 0) parts.push(`~${c.updated}`)
  if (parts.length === 0) return 'no changes'
  return `${parts.join(' / ')} plugins`
}
