// poller/src/main.ts
import { Octokit } from '@octokit/rest'
import { resolve } from 'node:path'
import { diff } from './differ.js'
import { registerSources } from './sources/index.js'
import type { CatalogEntry, Event } from './sources/types.js'
import { buildCatalog, writeCatalog } from './writers/catalog.js'
import { writeDigest, renderDigest } from './writers/digest-md.js'
import { appendEvents, readAllEvents } from './writers/events.js'
import { readSnapshot, writeSnapshot } from './writers/snapshot.js'
import { writeArtifacts } from './writers/artifacts.js'
import { writeFileAtomic } from './writers/fs-utils.js'
import { enrichStars } from './enrich-stars.js'

const REPO_ROOT = resolve(process.cwd(), '..')
// `npm run poll` is invoked with cwd = poller/, so repo root is one level up.

const PATHS = {
  snapshot: `${REPO_ROOT}/state/snapshot.json`,
  events: `${REPO_ROOT}/state/events.jsonl`,
  catalog: `${REPO_ROOT}/catalog/data.json`,
  digestDir: `${REPO_ROOT}/digests`,
  artifactDir: `${resolve(process.cwd(), 'out')}`,
}

async function main(): Promise<void> {
  const now = new Date().toISOString()
  const date = now.slice(0, 10)

  const token = process.env.GITHUB_TOKEN
  if (!token) {
    console.error('[poller] GITHUB_TOKEN not set')
    process.exit(1)
  }

  const octokit = new Octokit({ auth: token })
  const sources = registerSources(octokit)

  console.log(`[poller] fetching from ${sources.length} source(s)`)
  const fetched: CatalogEntry[] = []
  for (const source of sources) {
    const entries = await source.fetch()
    console.log(`[poller] ${source.id}: ${entries.length} entries`)
    fetched.push(...entries)
  }

  await enrichStars(fetched, octokit)

  const prevSnapshot = await readSnapshot(PATHS.snapshot)

  if (!prevSnapshot) {
    console.log('[poller] bootstrap mode: no prior snapshot, writing initial state')
    await writeSnapshot(PATHS.snapshot, fetched, now)
    const catalog = buildCatalog(fetched, [], now)
    await writeCatalog(PATHS.catalog, catalog)

    // Bootstrap writes only a commit message — no events, no digest, no issue.
    // The workflow gates issue creation on the existence of poller/out/issue-title.txt,
    // so not creating it is how we say "don't open an issue".
    const bootstrapCommitMsg =
      `chore: bootstrap initial snapshot (${fetched.length} entries)\n\n` +
      `Auto-generated by daily-poll.yml (bootstrap mode).\n`
    await writeFileAtomic(`${PATHS.artifactDir}/commit-message.txt`, bootstrapCommitMsg)
    console.log('[poller] bootstrap complete')
    return
  }

  const events: Event[] = diff(prevSnapshot, fetched, now)

  // Always rewrite snapshot & catalog (star counts change even without diff events)
  await writeSnapshot(PATHS.snapshot, fetched, now)

  const allEvents = events.length > 0
    ? await appendEvents(PATHS.events, events).then(() => readAllEvents(PATHS.events))
    : await readAllEvents(PATHS.events)

  const catalog = buildCatalog(fetched, allEvents, now)
  await writeCatalog(PATHS.catalog, catalog)

  if (events.length === 0) {
    const msg = `chore: update star counts (${date})\n\nNo additions or metadata changes.\n`
    await writeFileAtomic(`${PATHS.artifactDir}/commit-message.txt`, msg)
    console.log('[poller] no diff events (snapshot/catalog updated for stars)')
    return
  }

  const addedCount = events.filter((e) => e.type === 'added').length
  const removedCount = events.filter((e) => e.type === 'removed').length
  const updatedCount = events.filter((e) => e.type === 'updated').length
  console.log(`[poller] ${addedCount} added, ${removedCount} removed, ${updatedCount} updated`)

  const digestPath = `${PATHS.digestDir}/${date}.md`
  await writeDigest(digestPath, events, date)

  const digestMd = renderDigest(events, date)
  await writeArtifacts(
    {
      commitMessage: `${PATHS.artifactDir}/commit-message.txt`,
      issueTitle: `${PATHS.artifactDir}/issue-title.txt`,
      issueBody: `${PATHS.artifactDir}/issue-body.md`,
    },
    events,
    date,
    digestMd,
  )

  console.log('[poller] done')
}

main().catch((err: unknown) => {
  console.error('[poller] fatal:', err)
  process.exit(1)
})
